name: dynamic_type

environment:
  sdk: ">=1.24.0 <2.0.0"

transformers:
  - $dart2js:
      commandLineOptions:
        # Emits a .info.json file for analysis.
        - --dump-info

        # Useful to make --dump-info/dart2js more resemble user-code.
        - --disable-inlining

        # Basically every shipped dart2js application adds this.
        - --trust-type-annotations
        - --trust-primitives

      # Makes outputted code readable.
      minify: false
